### PR TITLE
Nuemah-Kremer branch completed

### PR DESCRIPTION
**Pull request by YaelNueKr**

### CODE REVIEW

**Comment by wlpotter** [comment]
@YaelNueKr just to confirm, this pull request includes all of the edits? (just want to make sure since it wasn't clear from its title)

**Comment by YaelNueKr** [comment]
@wlpotter It seems to be the case. I don't know why this happened. I will close it.

**Comment by YaelNueKr** [comment]
Unsure what to do about this - the issue was because I use mac, but for something it dragged on.

**Comment by wlpotter** [comment]
Thanks for confirming this @YaelNueKr

**Review by wlpotter — APPROVED** [review]
Ready to pull into development

**Pull request merged**
